version: "3"
services:
  workspace:
    tty: true
    build:
      context: .
      args:
        PUID: "${PUID:-1000}"
        PGID: "${PGID:-1000}"
    volumes:
      - .:/app
      - ~/.composer:/home/user/.composer